services:
  laravel-docker:
    container_name: Afrofrenchtouch
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_docker
    ports:
      - 3308:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_HOST=mysql_db
      - PMA_PORT=3306
